name = "monorepo-template"
main = "apps/web/.vercel/output/static"
compatibility_date = "2024-04-29"

[build]
command = "bun run build --filter web && cd apps/web && npx @cloudflare/next-on-pages@1"
cwd = "./"
watch_dir = "./apps/web"

[env.production]
vars = { NEXT_ON_PAGES_PACKAGE_MANAGER = "bun" }
